### ISSUE TITLE
Unhandled error in response

### ISSUE THREAD

**Issue by eduardomecchiafernandez** [msaaddev/who-unfollowed-me#3]
The script worked fine on Windows 10, but I get this output after switching to Windows 11:

‼  WARNING  Following folk/s have unfollowed you recently.
× Fetching GitHub followers
C:\Users\Eduardo\AppData\Roaming\npm\node_modules\who-unfollowed-me\utils\cli.js:38
                if (error.response.status === 404) {
                                   ^

TypeError: Cannot read properties of undefined (reading 'status')
    at module.exports (C:\Users\Eduardo\AppData\Roaming\npm\node_modules\who-unfollowed-me\utils\cli.js:38:22)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async module.exports (C:\Users\Eduardo\AppData\Roaming\npm\node_modules\who-unfollowed-me\index.js:29:2)

**Comment by msaaddev** [comment]
Thanks for letting me know. I will fix it ASAP.

**Comment by msaaddev** [comment]
@eduardomecchia I have launched a new release. Kindly update the CLI and try again.

**Comment by eduardomecchiafernandez** [comment]
Works fine now, thank you!!
